baseurl: https://cerr.cc
theme: stack
title: やれやれ DA✰ZE
publishDir: ..
paginate: 10


permalinks:
    post: /post/:slug/
    page: /:slug/


params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: favicon.png

    footer:
        since: 2022
        customText: All Right Abandoned.

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji: 🐟
        subtitle: Yet anothor cyber nyandog.
        avatar:
            enabled: true
            local: true
            src: img/avatar.jpg

    article:
        math: false
        toc: true
        readingTime: false
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 100
            - type: tag-cloud
              params:
                  limit: 100
        page:
            - type: toc

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        toggle: true
        default: auto # Available values: auto, light, dark

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true


# See https://docs.stack.jimmycai.com/configuration/custom-menu.html
menu:
    main: []
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/dev2ero
          params:
              icon: brand-github

        - identifier: twitter
          name: Twitter
          url: https://twitter.com/dev2ero
          params:
              icon: brand-twitter

        - identifier: mail
          name: Mail
          url: mailto:dev2ero@foxmail.com
          params:
              icon: mail


related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100
        - name: categories
          weight: 200


markup:
    goldmark:
        renderer:
            unsafe: true
    tableOfContents:
        startLevel: 1
        endLevel: 6
        ordered: true
    highlight:
        noClasses: false
        codeFences: true
        guessSyntax: true
        lineNos: true
        lineNoStart: 1
        lineNumbersInTable: true
        tabWidth: 4
