baseURL = "https://dev2ero.github.io/"
title = "Zikey Vi"
copyright = "© 2022, Zikey Vi"
paginate = 4
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin"
publishDir = ".."
watch = true

[params]
  description = "Zikey Vi's Blog Site"
  featured = true
  cssonly = false

  [params.socials]
    email = "mailto:dev2ero@foxmail.com"
    github = "https://github.com/dev2ero"
    twitter = "https://twitter.com/dev2ero"
    bilibili = "https://space.bilibili.com/210892014"
    zhihu = "https://www.zhihu.com/people/izay01"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/main/about/"
    weight = 1

  [[menu.main]]
    name = "Board"
    url = "/main/board/"
    weight = 2

  [[menu.main]]
    name = "Friend"
    url = "/main/friend/"
    weight = 3

  [[menu.main]]
    name = "Utils"
    url = "/main/utils/"
    weight = 4


[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true